### ISSUE TITLE
LogConfig.config must be a dictionary

### ISSUE THREAD

**Issue by flower-pot** [rancher/rancher-compose#54]
I wanted to try out the log-driver and log-opt added in #1388 and #1665 to `docker-compose`. In the rancher forum I was told these features are supported in rancher.

My `docker-compose.yml` looks like this:

```
web:
  image: flowerpot/goif
  ports:
    - "8080:8080"
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://syslog-server:514"
```

> the `syslog-server` host is is an actual remote syslog server :wink: 

However, when I do `rancher-compose up` I get the following error (in the UI):

```LogConfig.config must be a dictionary```

It works using `docker-compose`.

Versions:

```
rancher-server version v0.31.0
rancher-compose version v0.2.5
```
