### ISSUE TITLE
rancher-compose does not discard build key if image key is set in local file (extends functionality)

### ISSUE THREAD

**Issue by bymodude** [rancher/rancher-compose#68]
docker-compose behaviour is like this, should rancher-compose not follow same behaviour?
 https://docs.docker.com/compose/extends/ 
>In the case of build and image, using one in the local service causes Compose to discard the other, if it was defined in the original service.

with the following files and using ```rancher-compose -f production.xml``` it is trying to upload local build context to s3, so its using ```build: .``` instead of ```image: test```

docker-compose.yml:
```
test
  build: .
```
production.yml
```
test
  extends:
    file: docker-compose.yml
    service: test
  image: test
```
