### ISSUE TITLE
attr: scale

### ISSUE THREAD

**Issue by fentas** [rancher/rancher-compose#96]
Question:
I define services with the attr `scale` expecting if there is e.g. a 3 that it will start 3 containers.
But no luck. It is always 1. Intended?
Example:
```yaml
mongo-replSet-rs0:
  scale: 3
  container_name: mongo-replSet-rs0
  image: mongo:3.0
  command: mongod --replSet rs0
  stdin_open: true
  tty: true
  restart: always
  ports:
    - "27017:27017"
    - "28017:28017"
  volumes:
    - /data/db:/data/db
  labels:
    io.rancher.scheduler.affinity:host_label: template=mongod
    io.rancher.container.pull_image: always
  health_check:
    port: 28017
    request_line: GET / HTTP/1.0
    interval: 2000
    healthy_threshold: 2
    unhealthy_threshold: 3
    response_timeout: 2000
```

p.s.: using `rancher-compose` 0.4.0 + latest `rancher-server`
